server:
  port: 8405

spring:
  application:
    name: service-gateway

eureka:
  client:
    service-url:
      defaultZone: http://120.24.30.252:7001/eureka/

## Spring Cloud Gateway的日志配置
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
