server:
  port: 8405

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes: #当访问 http://localhost:8401/heartbeat,直接转发到 http://heartbeat.top/
        - id: baidu_route
          uri: http://heartbeat.top:80/
          predicates:
            - Path=/heartbeat

eureka:
  client:
    service-url:
      defaultZone: http://120.24.30.252:7001/eureka/

logging: ## Spring Cloud Gateway的日志配置
 level:
   org.springframework.cloud.gateway: TRACE
   org.springframework.http.server.reactive: DEBUG
   org.springframework.web.reactive: DEBUG
   reactor.ipc.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
