server:
  port: 8305

spring:
  application:
    name: service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://120.24.30.252:7001/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream

# Feign默认关闭了对Hystrix的支持
feign:
  hystrix:
    enabled: true
