server:
  port: 8205

spring:
  application:
    name: service-provider
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://120.24.30.252:3306/aquarius?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT                    # 数据库名称
      username: aquarius
      password: Bsxa3mak7PA4fhYD

  # redis 配置
  redis:
    host: 120.24.30.252
    port: 6379
    timeout: 6s #连接池超时时长
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空闲连接
    password: 1SrEQwqD7Klx90mY

mybatis-plus:
  global-config:
    #mybatis原生配置
    configuration:
      #驼峰下划线转换
      map-underscore-to-camel-case: true
      #或者
      mapUnderscoreToCamelCase: true
      #设为true表示开启驼峰转换，两种配置方法都可以。但如果同时配置，
      #前者mybatis.configuration.mapUnderscoreToCamelCase的优先级更高
      #不开启二级缓存
      cache-enabled: true

#shiro:
#  web:
#    enabled: false

logging:
  level:
    root: info #日志级别 root表示所有包，也可以单独配置具体包 fatal error warn info debug trace off
  file:
    name: ${logging.file.path}/${spring.application.name}.log #日志文件名称
    path: ../logs/${spring.application.name} #日志文件路径

eureka:
  client:
    service-url:
      defaultZone: http://120.24.30.252:7001/eureka/
